version: '3'
services:
  client:
    image: "toninokastelan/hciblog-client"
    hostname: client
  api:
    image: "toninokastelan/hciblog-api"
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_HOST=POSTGRES_HOST
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_PORT=$POSTGRES_PORT
  nginx:
    image: "toninokastelan/hciblog-nginx"
    hostname: nginx
    ports:
      - "80:80"
