version: '3'
services:
  api:
    image: "toninokastelan/hci-blog-api"
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_PORT=$POSTGRES_PORT
      - SECRET_KEY=$SECRET_KEY
  nginx:
    image: "toninokastelan/hci-blog-nginx"
    hostname: nginx
    ports:
      - "80:80"
