version: '3'
services:
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    hostname: client
    volumes:
      - /home/node/app/node_modules
      - ./client:/home/node/app
    environment:
      WDS_SOCKET_PORT: 0
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    hostname: api
    environment:
      REDIS_HOST: hci_redis
      REDIS_PORT: 6379
      POSTGRES_USER:
      POSTGRES_HOST: hci_postgres
      POSTGRES_DB: hci_blog
      POSTGRES_PASSWORD: 2022hciblog2023
      POSTGRES_PORT: 5432
    volumes:
      - ./server:/app
  nginx:
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    hostname: nginx
    ports:
      - "80:80"