version: '3'
services:
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    hostname: client
    volumes:
      - /home/node/app/node_modules
      - ./client:/home/node/app
    environment:
      WDS_SOCKET_PORT: 0
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    hostname: api
    environment:
      REDIS_HOST: blog_cache
      REDIS_PORT: 6379
      POSTGRES_USER: blogger
      POSTGRES_HOST: blog_db
      POSTGRES_DB: blog_db
      POSTGRES_PASSWORD: 2022hciblog2023
      POSTGRES_PORT: 5432
    volumes:
      - ./server:/app
  blog_db:
    hostname: blog_db
    image: postgres:latest
    environment:
      - POSTGRES_DB=blog_db
      - POSTGRES_USER=blogger
      - POSTGRES_PASSWORD=2022hciblog2023
    volumes:
      - database:/var/lib/postgresql/data
  blog_redis:
    hostname: blog_cache
    image: redis:latest
  nginx:
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    hostname: nginx
    ports:
      - "80:80"

volumes:
  database:
