FROM python:3.10-alpine

WORKDIR "/app"

COPY ./requirements.txt ./

RUN apk update && apk add git &&\
    pip install --upgrade pip && \
    pip install -r requirements.txt

COPY . /app

RUN pip install -e .

CMD ["uvicorn", "src.app:app", "--debug", "--reload", "--host", "0.0.0.0", "--port", "8000"]
