name: Deploy Backend
on:
  push:
    branches:
      - production_be
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync repo
        uses: actions/checkout@v2
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build api
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/hci-blog-api ./server
      - name: Build nginx server
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/hci-blog-nginx ./nginx
      - name: Push api
        run: docker push ${{ secrets.DOCKER_USERNAME }}/hci-blog-api
      - name: Push nginx
        run: docker push ${{ secrets.DOCKER_USERNAME }}/hci-blog-nginx
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Sync repo
        uses: actions/checkout@v2
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*' -x '.env' -x 'client' 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: hci-blog
          environment_name: Hciblog-env
          existing_bucket_name: elasticbeanstalk-eu-central-1-979004399329
          region: eu-central-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
